# Generated by Django 5.0.6 on 2024-07-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
