# Generated by Django 5.0.6 on 2024-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='fullname',
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
