# Generated by Django 5.0.6 on 2024-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
