# Generated by Django 5.0.6 on 2024-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contactus_email_alter_contactus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
