# Generated by Django 5.0.6 on 2024-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
