# Generated by Django 5.0.6 on 2024-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='counter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
