# Generated by Django 5.0.6 on 2024-07-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contactus_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='counter',
        ),
    ]
